# Generated by Django 3.0.5 on 2020-08-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0003_auto_20200812_1208'),
        ('myresources_profil', '0002_auto_20200805_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myresources.Department'),
        ),
    ]
