# Generated by Django 3.0.5 on 2020-08-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresources_profil', '0004_auto_20200822_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'teacher'), (4, 'admin'), (5, 'super admin')], primary_key=True, serialize=False),
        ),
    ]
