# Generated by Django 3.0.5 on 2020-06-06 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_postal', models.CharField(max_length=10, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrow', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_delivery', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_classe', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_course', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=50, unique=True)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10, unique=True)),
                ('is_student', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=255)),
                ('end', models.CharField(max_length=55)),
                ('color', models.CharField(default='1976d2', max_length=255)),
                ('is_valid', models.BooleanField(default=False)),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Classe')),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Course')),
                ('id_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myresources.Equipment')),
                ('id_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_failed', models.BooleanField(default=False)),
                ('id_schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myresources.Schedule')),
                ('id_teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myresources.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('id_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Course')),
                ('matricule_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Students')),
            ],
        ),
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Course')),
                ('matricule_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(to='myresources.Teacher'),
        ),
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Equipment')),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Borrowing')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='course',
            field=models.ManyToManyField(to='myresources.Course'),
        ),
        migrations.CreateModel(
            name='CategoryCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50)),
                ('course', models.ManyToManyField(to='myresources.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryClasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('classe', models.ManyToManyField(to='myresources.Classe')),
            ],
        ),
        migrations.AddField(
            model_name='borrowing',
            name='matricule_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Teacher'),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Borrow'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='equipment',
            field=models.ManyToManyField(to='myresources.Equipment'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='teacher',
            field=models.ManyToManyField(to='myresources.Teacher'),
        ),
    ]
