# Generated by Django 3.0.5 on 2020-05-14 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_postal', models.CharField(max_length=10, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrow', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_delivery', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=10, unique=True)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_classe', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_course', models.CharField(max_length=10, unique=True)),
                ('entitled', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ManyToManyField(to='myresources.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('details', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='1976d2', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TokenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('date_naissance', models.DateTimeField(default=django.utils.timezone.now)),
                ('adress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myresources.Adress')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myresources.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myresources.Adress')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Classe')),
                ('id_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myresources.Schedule'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Course')),
                ('matricule_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Students')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_equipment', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Course')),
                ('matricule_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myresources.Schedule'),
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(to='myresources.Students'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(to='myresources.Teacher'),
        ),
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Equipment')),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Borrowing')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myresources.Schedule'),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='matricule_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Teacher'),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Borrow'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='equipment',
            field=models.ManyToManyField(to='myresources.Equipment'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='teacher',
            field=models.ManyToManyField(to='myresources.Teacher'),
        ),
    ]
