# Generated by Django 3.0.5 on 2020-06-06 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationschedule',
            name='id_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Teacher'),
        ),
    ]
