# Generated by Django 3.0.5 on 2020-04-24 08:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('code_postal', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
                ('quartier', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('code_categorie', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_categorie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('code_classe', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('code_cours', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('intitulé', models.CharField(max_length=50)),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Emploi_de_temps',
            fields=[
                ('code_Et', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('date_emprunt', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_remise', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('matricule_ens', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateTimeField(default=django.utils.timezone.now)),
                ('adresse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myresources.Adresse')),
                ('emploi_de_temps', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myresources.Emploi_de_temps')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiants',
            fields=[
                ('matricule_et', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateTimeField(default=django.utils.timezone.now)),
                ('adresse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myresources.Adresse')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='Suivre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Cours')),
                ('matricule_et', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Etudiants')),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id_salle', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('classe', models.ManyToManyField(to='myresources.Classe')),
                ('emploi_de_temps', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myresources.Emploi_de_temps')),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('code_materiel', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Faire_emprunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule_ens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Enseignant')),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Emprunt')),
            ],
        ),
        migrations.AddField(
            model_name='emprunt',
            name='enseignant',
            field=models.ManyToManyField(to='myresources.Enseignant'),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='materiel',
            field=models.ManyToManyField(to='myresources.Materiel'),
        ),
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Cours')),
                ('matricule_ens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Enseignant')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='emploi_de_temps',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myresources.Emploi_de_temps'),
        ),
        migrations.AddField(
            model_name='cours',
            name='enseignant',
            field=models.ManyToManyField(to='myresources.Enseignant'),
        ),
        migrations.AddField(
            model_name='cours',
            name='etudiant',
            field=models.ManyToManyField(to='myresources.Etudiants'),
        ),
        migrations.CreateModel(
            name='Concerner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Materiel')),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Emprunt')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='emploi_de_temps',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myresources.Emploi_de_temps'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('matricule_admin', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateTimeField(default=django.utils.timezone.now)),
                ('adresse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myresources.Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Abriter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Classe')),
                ('id_salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Salle')),
            ],
        ),
    ]
