# Generated by Django 3.0.5 on 2020-05-14 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='start_date',
            new_name='start',
        ),
    ]
