# Generated by Django 3.0.5 on 2020-08-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0002_auto_20200805_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='praticals_works',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='level',
            name='course',
            field=models.ManyToManyField(to='myresources.Course'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='filiere_categorie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myresources.FiliereCategorie'),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_code',
            field=models.CharField(max_length=20),
        ),
    ]
