# Generated by Django 3.0.5 on 2020-06-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0002_auto_20200606_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationschedule',
            name='message',
            field=models.TextField(default="'Reservation en attente'"),
        ),
    ]
