# Generated by Django 3.0.5 on 2020-06-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0003_reservationschedule_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationschedule',
            name='message',
            field=models.TextField(default='Reservation en attente'),
        ),
    ]
