# Generated by Django 3.0.5 on 2020-08-12 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0004_auto_20200812_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeschedule',
            name='schedule',
        ),
        migrations.AddField(
            model_name='typeschedule',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myresources.Schedule'),
        ),
    ]
