# Generated by Django 3.0.5 on 2020-08-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0006_auto_20200812_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='id_equipment',
        ),
    ]
