# Generated by Django 3.0.5 on 2020-05-21 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0006_auto_20200520_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='schedule',
        ),
        migrations.AddField(
            model_name='classe',
            name='name_classe',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_classe',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='myresources.Classe'),
            preserve_default=False,
        ),
    ]
