# Generated by Django 3.0.5 on 2020-08-13 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0007_remove_schedule_id_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='id_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myresources.Level'),
        ),
    ]
