# Generated by Django 3.0.5 on 2020-05-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0007_auto_20200521_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='code_classe',
            field=models.CharField(choices=[('ICTL1', 'ICTL1'), ('ICTL2', 'ICTL2'), ('ICTL3', 'ICTL3')], default='ICTL1', max_length=10),
        ),
    ]
