# Generated by Django 3.0.5 on 2020-05-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0008_auto_20200521_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='name_classe',
        ),
        migrations.AlterField(
            model_name='classe',
            name='code_classe',
            field=models.CharField(choices=[("[('ICTL1', 'ICTL1'), ('ICTL2', 'ICTL2'), ('ICTL3', 'ICTL3')]", 'Classe Choice'), ('ICTL1', 'ICT Licence 1'), ('ICTL2', 'ICT Licence 2'), ('ICTL3', 'ICT Licence 3')], default='ICTL1', max_length=80),
        ),
    ]
