# Generated by Django 3.0.5 on 2020-08-13 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0008_schedule_id_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeschedule',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myresources.TypeSchedule'),
        ),
    ]
