# Generated by Django 3.0.5 on 2020-05-21 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0009_auto_20200521_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='id_classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Classe'),
        ),
    ]
