# Generated by Django 3.0.5 on 2020-05-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0010_auto_20200521_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='code_classe',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
