# Generated by Django 3.0.5 on 2020-08-17 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myresources', '0011_schedule_id_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_user_schedule', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
