# Generated by Django 3.0.5 on 2020-05-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0012_auto_20200521_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
