# Generated by Django 3.0.5 on 2020-05-21 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0013_auto_20200521_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('id_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Equipment', unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='code_room',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='id_room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Shelter',
        ),
    ]
