# Generated by Django 3.0.5 on 2020-08-18 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0013_auto_20200818_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeschedule',
            name='type_reservation',
        ),
        migrations.AddField(
            model_name='schedule',
            name='type_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_reservation', to='myresources.TypeSchedule'),
        ),
    ]
