# Generated by Django 3.0.5 on 2020-08-18 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myresources', '0014_auto_20200818_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_user_schedule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='typeschedule',
            name='type',
            field=models.CharField(choices=[(1, 'cours'), (2, 'cc'), (3, 'rattrapage'), (4, 'TD'), (5, 'sn'), (6, 'reservation')], default=1, max_length=20, unique=True),
        ),
    ]
