# Generated by Django 3.0.5 on 2020-05-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0014_auto_20200521_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='number',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
