# Generated by Django 3.0.5 on 2020-08-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0016_auto_20200819_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeschedule',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'cours'), (2, 'cc'), (3, 'rattrapage'), (4, 'TD'), (5, 'sn'), (6, 'reservation')], default=1, unique=True),
        ),
    ]
