# Generated by Django 3.0.5 on 2020-08-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0017_auto_20200819_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeschedule',
            name='value',
            field=models.CharField(default='COURS', max_length=55),
            preserve_default=False,
        ),
    ]
