# Generated by Django 3.0.5 on 2020-08-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0019_auto_20200819_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeschedule',
            name='value',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
