# Generated by Django 3.0.5 on 2020-08-21 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myresources', '0020_auto_20200819_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'cours'), (2, 'cc'), (3, 'rattrapage'), (4, 'TD'), (5, 'sn'), (6, 'reservation')], default=1, unique=True)),
                ('value', models.CharField(default='blue', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=200)),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.CategorieNotifications')),
                ('id_emetter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresources.Schedule')),
                ('id_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
