# Generated by Django 3.0.5 on 2020-08-22 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myresources', '0022_auto_20200821_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='id_emetter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
