# Generated by Django 3.0.5 on 2020-08-22 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myresources', '0024_auto_20200822_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='id_cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myresources.CategorieNotifications', to_field='type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notifications',
            name='id_emetter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
