# Generated by Django 3.0.5 on 2020-08-23 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0027_auto_20200822_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='id_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myresources.Department'),
            preserve_default=False,
        ),
    ]
