# Generated by Django 3.0.5 on 2020-08-23 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresources', '0029_auto_20200823_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='type_reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_reservation', to='myresources.TypeSchedule', to_field='type'),
        ),
    ]
